# Generated by Django 3.2.16 on 2022-12-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20221223_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('1', 'Clothing'), ('2', 'Shoes'), ('3', 'Vehicle'), ('4', 'Accesories'), ('5', 'Watches'), ('6', 'Sports'), ('7', 'Home'), ('8', 'Toys'), ('9', 'Business'), ('10', 'Health & Beauty'), ('11', 'Pets'), ('12', 'Other')], default='12', max_length=2),
        ),
    ]
