# Generated by Django 4.1.3 on 2023-05-09 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_auto_20221231_0110"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="highest_bidder_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
