# Generated by Django 4.1.3 on 2023-05-09 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_auctionlisting_highest_bidder_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="highest_bidder_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
