# Generated by Django 4.1.3 on 2023-05-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_remove_auctionlisting_comment_auctionlisting_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="auction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="auctions.auctionlisting",
            ),
        ),
    ]
