# Generated by Django 4.1.3 on 2023-05-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_remove_auctionlisting_comment_comment_auction"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
