# Generated by Django 4.1.3 on 2023-05-10 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_comment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
